name: Codeowners

on:
  pull_request_target:
    # See the comment at the same location in ./check-by-name.yml
    types: [opened, synchronize, reopened, edited]

# This workflow depends on a GitHub App with the following permissions:
# - Repository > Administration: read-only
# - Repository > Pull Requests: read-write
# The App needs to be installed on this repository
# the OWNER_APP_ID repository variable needs to be set
# the OWNER_APP_PRIVATE_KEY repository secret needs to be set

jobs:
  check-owners:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        path: base

    - name: Build codeowners validator
      # We run the result of this with access to secrets later, so it's important to trust this!
      run: nix-build base/ci -A codeownersValidator

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        # This GitHub App needs Organization/Members/read-only access
        # to figure out who's part of the team
        app-id: ${{ vars.OWNER_APP_ID }}
        private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.number }}/merge
        path: pr

    - name: Validate codeowners
      run: result/bin/codeowners-validator
      env:
        GITHUB_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
        REPOSITORY_PATH: pr
        OWNER_CHECKER_REPOSITORY: ${{ github.repository }}
        EXPERIMENTAL_CHECKS: "notowned,avoid-shadowing"
        # Uncomment this to require all paths to have a code owner
        #OWNER_CHECKER_ALLOW_UNOWNED_PATTERNS: "false"

  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build review request package
        run: nix-build ci -A requestReviews

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # This GitHub App needs Organization/Members/read-only access
          # to figure out who's part of the team
          app-id: ${{ vars.OWNER_APP_ID }}
          private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}

      - name: Request reviews
        run: ./result/bin/request-reviews.sh ${{ github.repository }} ${{ github.event.number }} .github/OWNERS
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
