name: Request reviews from code owners

on:
  pull_request_target:
    # See the comment at the same location in ./check-by-name.yml
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  request:
    name: Request reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Build review request package
        run: nix-build ci -A requestReviews
      - name: Request reviews
        run: ./result/bin/request-reviews.sh ${{ github.repository }} ${{ github.event.number }} .github/OWNERS
        env:
          GH_TOKEN: ${{ github.token }}
